### ISSUE TITLE
Passkey Support Prior to Android 14

### ISSUE THREAD

**Issue by BoredEgg** [Dashlane/android-passkey-example#3]
I was reading through the docs and it seems as though passkeys is only available on Android 14 onward for native support.

As for mobile-web it looks like we can create passkeys Android 9+ via the mobile-web-app, which we can use to scan QR codes for the web app (makes sense because they're both on web - so there's no (web to native app) linking needed.)

In the docs https://developer.android.com/training/sign-in/passkeys
they say that the second import is needed for credential support from play services for Android 13 < 

![Screenshot 2023-06-21 at 5 33 28 PM](https://github.com/Dashlane/android-passkey-example/assets/136927783/4f4e6021-523c-4359-a818-ec65bfd21b1a)

I tried running the app with a lower min/target SDK version (Android 11) and get: 
"Account Creation Error -> The incoming request could not be validated"

So my question is why do they include 
`implementation("androidx.credentials:credentials-play-services-auth:1.2.0-alpha05")` in the docs if native passkey support isn't available Android 13 <.

And if it is available what's missing from this repo to support older android versions.

**Comment by GuillaumeBouxin** [comment]
Passkeys are available starting with Android 9, but only with Google password manager. What we wanted to demo with this repository is the availability to use a third-party provider (like Dashlane) to manage passkey.

But it would be nice if we also support Android versions under 14, unfortunately, I don't have any clue about the error you mentioned, maybe it's because this application doesn't have any digital asset links, as it looks like mandatory -> https://developer.android.com/training/sign-in/passkeys#add-support-dal

**Comment by BoredEgg** [comment]
Ahhh i see, that makes sense
I realized my mix up earlier, hopefully they get to supporting under Android 14.
Thanks for the clarification

**Comment by GuillaumeBouxin** [comment]
Hey! I've updated the project to make it work under Android 14 ;)
